{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- $values := .Values }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redpanda.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    helm.sh/chart: {{ template "redpanda.chart" . }}
    app.kubernetes.io/name: {{ template "redpanda.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/component: {{ template "redpanda.name" . }}
{{- with .Values.commonLabels }}
  {{- toYaml . | nindent 4 }}
{{- end }}
data:
{{- if (include "redpanda.semver" . | semverCompare ">=22.1.4") }}
  bootstrap.yaml: |
{{- if .Values.auth.sasl.enabled }}
      enable_sasl: true 
  {{- with .Values.auth.sasl.users }}
      superusers: ['{{ (first .).name }}']
  {{- end }}
{{- end }}
 {{- with .Values.config.cluster }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
  {{- with .Values.config.tunable }}
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end }}
  redpanda.yaml: |
    config_file: /etc/redpanda/redpanda.yaml
    {{- if gt (len .Values.license_key) 0 }}
    license_key: {{ .Values.license_key }}
    {{- end }}
    {{- if gt (len .Values.organization) 0 }}
    organization: {{ .Values.organization }}
    {{- end }}
    redpanda:
{{- if not (include "redpanda.semver" . | semverCompare ">=22.1.4") }}
{{- if .Values.auth.sasl.enabled }}
  {{- with .Values.auth.sasl.users }}
      superusers:
    {{ toYaml . | indent 8 }}
  {{- end }}
{{- end }}
{{- if not (eq (toYaml .Values.config) "null") }}
  {{ toYaml .Values.config | indent 4 }}
{{- end }}
{{- end }}
{{- if .Values.listeners.admin.enabled }}
      admin:
        address: {{ .Values.listeners.admin.address }}
        name: admin
        port: {{ .Values.listeners.admin.port }}
  {{- $adminTlsEnabled := include "admin-tls-enabled" . }}
  {{- if eq $adminTlsEnabled "true" }}
      admin_api_tls:
      - cert_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.admin.tls.cert }}/tls.crt
        enabled: true
        key_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.admin.tls.cert }}/tls.key
        name: admin
    {{- if .Values.listeners.admin.tls.requireClientAuth }}
        require_client_auth: true
    {{- end }}
        truststore_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.admin.tls.cert }}/ca.crt
  {{- end }}
{{- else }}
      enable_admin_api: false
{{- end }}
      enable_sasl: {{ .Values.auth.sasl.enabled }}
      kafka_api_tls:
{{- range $i, $listener := .Values.listeners.kafka.endpoints }}
  {{- if hasKey $listener "tls" }}
    {{- if or $listener.tls.enabled (and (empty $listener.tls.enabled) $values.auth.tls.enabled) }}
      - cert_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.crt
        enabled: true
        key_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.key
        name: {{ $listener.name }}
        require_client_auth: {{ $listener.tls.requireClientAuth }}
        truststore_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/ca.crt
    {{- end }}
  {{- end }}
{{- end }}
{{- if hasKey .Values.listeners.rpc "tls" }}
  {{- if or .Values.listeners.rpc.tls.enabled (and (empty .Values.listeners.rpc.tls.enabled) .Values.auth.tls.enabled) }}
      rpc_server_tls:
        enabled: true
        require_client_auth: {{ .Values.listeners.rpc.tls.requireClientAuth }}
        cert_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.rpc.tls.cert }}/tls.crt
        key_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.rpc.tls.cert }}/tls.key
        truststore_file: {{ printf "/etc/tls/certs/%s" .Values.listeners.rpc.tls.cert }}/ca.crt
  {{- end }}
{{- end }}
      seed_servers:
{{- range untilStep 0 (.Values.statefulset.replicas|int) 1 }}
      - host:
          address: "{{ template "redpanda.fullname" $ }}-{{ . }}.{{ template "redpanda.internal.domain" $ }}"
          port: {{ $values.listeners.rpc.port }}
{{- end }}
{{- if not (eq (toYaml .Values.config.node) "null") }}
  {{ toYaml .Values.config.node | indent 4 }}
{{- end }}
    rpk:
{{ toYaml .Values.rpk | indent 6 }}
{{- if .Values.listeners.rest.enabled }}
    pandaproxy:
      pandaproxy_api_tls:
  {{- range $i, $listener := .Values.listeners.rest.endpoints }}
    {{- if hasKey $listener "tls" }}
      {{- if or (default false $listener.tls.enabled) (and (not (hasKey $listener.tls "enabled")) $values.auth.tls.enabled) }}
      - cert_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.crt
        enabled: true
        key_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.key
        name: {{ $listener.name }}
        require_client_auth: {{ $listener.tls.requireClientAuth }}
        truststore_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/ca.crt
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- if .Values.listeners.schemaRegistry.enabled }}
    schema_registry:
      schema_registry_api_tls:
  {{- range $i, $listener := .Values.listeners.schemaRegistry.endpoints }}
    {{- if hasKey $listener "tls" }}
      {{- if or (default false $listener.tls.enabled) (and (not (hasKey $listener.tls "enabled")) $values.auth.tls.enabled) }}
      - cert_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.crt
        enabled: true
        key_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/tls.key
        name: {{ $listener.name }}
        require_client_auth: {{ $listener.tls.requireClientAuth }}
        truststore_file: {{ printf "/etc/tls/certs/%s" $listener.tls.cert }}/ca.crt
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
