{{- if (include "tls-enabled" . | fromJson).bool }}
  {{- $root := deepCopy . }}
  {{- $service := include "redpanda.fullname" . -}}
  {{- $ns := .Release.Namespace -}}
  {{- $domain := .Values.clusterDomain | trimSuffix "." -}}
  {{- $listeners := .Values.listeners -}}
  {{- $values := .Values }}
  {{- range $name, $data := .Values.tls.certs }}
    {{- $d := $data.duration }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  namespace: {{ $ns | quote }}
  labels:
{{- with include "full.labels" $root }}
  {{- . | nindent 4 }}
{{- end }}
spec:
  dnsNames:
  - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc.%s" $service $ns $domain }}
  - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc" $service $ns }}
  - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s" $service $ns }}
  - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc.%s" $service $ns $domain }}"
  - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc" $service $ns }}"
  - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s" $service $ns }}"
  - {{ printf "%s.%s.svc.%s" $service $ns $domain }}
  - {{ printf "%s.%s.svc" $service $ns }}
  - {{ printf "%s.%s" $service $ns }}
  - {{ printf "*.%s.%s.svc.%s" $service $ns $domain | quote }}
  - {{ printf "*.%s.%s.svc" $service $ns | quote }}
  - {{ printf "*.%s.%s" $service $ns | quote }}
{{- if $values.external.domain }}
  - "*.{{ $values.external.domain }}"
{{- end }}
  duration: {{ $d | default "43800h" }}
  isCA: false
  commonName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  secretName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  privateKey:
    algorithm: ECDSA
    size: 256
    {{- if not (empty $data.issuerRef) }}
  issuerRef:
    {{- toYaml $data.issuerRef | nindent 4 }}
    group: cert-manager.io
    {{- else }}
  issuerRef:
    name: {{ template "redpanda.fullname" $ }}-{{ $name }}-root-issuer
    kind: Issuer
    group: cert-manager.io
    {{- end }}
  {{- end }}
{{- end }}
