{{/*
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements.  See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License.  You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/}}
{{- if (include "tls-enabled" . | fromJson).bool }}
  {{- $root := deepCopy . }}
  {{- $service := include "redpanda.servicename" . }}
  {{- $ns := .Release.Namespace }}
  {{- $domain := .Values.clusterDomain | trimSuffix "." }}
  {{- $listeners := .Values.listeners }}
  {{- $values := .Values }}
  {{- range $name, $data := .Values.tls.certs }}
    {{- if (empty $data.secretRef ) }}
      {{- $d := $data.duration }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  namespace: {{ $ns | quote }}
      {{- with include "full.labels" $root }}
  labels:
        {{- . | nindent 4 }}
      {{- end }}
spec:
  dnsNames:
      {{- if (empty $data.issuerRef) }}
    - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc.%s" $service $ns $domain }}
    - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc" $service $ns }}
    - {{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s" $service $ns }}
    - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc.%s" $service $ns $domain }}"
    - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s.svc" $service $ns }}"
    - "*.{{ template "redpanda.fullname" $ }}-cluster.{{ printf "%s.%s" $service $ns }}"
    - {{ printf "%s.%s.svc.%s" $service $ns $domain }}
    - {{ printf "%s.%s.svc" $service $ns }}
    - {{ printf "%s.%s" $service $ns }}
    - {{ printf "*.%s.%s.svc.%s" $service $ns $domain | quote }}
    - {{ printf "*.%s.%s.svc" $service $ns | quote }}
    - {{ printf "*.%s.%s" $service $ns | quote }}
      {{- end }}
      {{- if (tpl ($values.external.domain | default "") $) }}
    - "{{ tpl $values.external.domain $ }}"
    - "*.{{ tpl $values.external.domain $ }}"
      {{- end }}
  duration: {{ $d | default "43800h" }}
  isCA: false
  secretName: {{ template "redpanda.fullname" $ }}-{{ $name }}-cert
  privateKey:
    algorithm: ECDSA
    size: 256
      {{- if not (empty $data.issuerRef) }}
  issuerRef:
        {{- toYaml $data.issuerRef | nindent 4 }}
    group: cert-manager.io
      {{- else }}
  issuerRef:
    name: {{ template "redpanda.fullname" $ }}-{{ $name }}-root-issuer
    kind: Issuer
    group: cert-manager.io
      {{- end }}
    {{- end }}
  {{- end }}
---
  {{- $name := .Values.listeners.kafka.tls.cert }}
  {{- $data := get .Values.tls.certs $name }}
  {{- if and (empty $data.secretRef) (include "client-auth-required" . | fromJson).bool }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "redpanda.fullname" $ }}-client
  namespace: {{ $ns | quote }}
  {{- with include "full.labels" $root }}
  labels: {{- . | nindent 4 }}
  {{- end }}
spec:
  commonName: {{ template "redpanda.fullname" $ }}-client
  duration: {{ $data.duration | default "43800h" }}
  isCA: false
  secretName: {{ template "redpanda.fullname" $ }}-client
  privateKey:
    algorithm: ECDSA
    size: 256
  {{- if not (empty $data.issuerRef) }}
  issuerRef: {{- toYaml $data.issuerRef | nindent 4 }}
    group: cert-manager.io
  {{- else }}
  issuerRef:
    name: {{ template "redpanda.fullname" $ }}-{{ $name }}-root-issuer
    kind: Issuer
    group: cert-manager.io
  {{- end }}
  {{- end }}
{{- end }}
