---
apiVersion: redpanda.vectorized.io/v1alpha1
kind: Cluster
metadata:
  name: cluster-tls
spec:
  image: "docker.redpanda.com/redpandadata/redpanda"
  version: "latest"
  replicas: 3
  resources:
    requests:
      cpu: 1
      memory: 1.2Gi
    limits:
      cpu: 1
      memory: 1.2Gi
  configuration:
    rpcServer:
      port: 33145
    kafkaApi:
      - port: 9092
        tls:
          enabled: true
          requireClientAuth: true
    adminApi:
    - port: 9644
    pandaproxyApi:
    - port: 8082
    developerMode: true